/*
const int colortex0Format = R11F_G11F_B10F; //main color
const int colortex1Format = R32F;           //previous depth
const int colortex2Format = RGBA16F;        //taa + exposure in alpha
const int colortex3Format = RGBA8;          //(cloud/water map on deferred/gbuffer) | translucentMult & bloom & final color
const int colortex4Format = R8;             //volumetric cloud linear depth & volumetric light factor
const int colortex5Format = RGBA8_SNORM;    //normalM & scene image for water reflections
const int colortex6Format = RGBA8;          //smoothnessD & materialMask & skyLightFactor
const int colortex7Format = RGBA16F;        //(cloud/water map on gbuffer) | temporal filter
const int colortex8Format = RGBA8;          //smoothnessD & materialMask & skyLightFactor
const int colortex9Format = RGBA16F;        //physical sky buffer (raymarched atmosphere)
const int colortex10Format = RGBA16F; 
const int colortex11Format = RGBA16F;       //global illumination
const int colortex12Format = RGBA16F;       //cloud render (combined blur)
const int colortex13Format = R32F;          //cloud depth
const int colortex14Format = RGBA16F;       //blurred cloud data (from deferred6)
const int colortex15Format = RGB16F;        //TAA neighborhood max bounds
*/
const bool colortex0Clear = true;
const bool colortex1Clear = false;
const bool colortex2Clear = false;
const bool colortex3Clear = true;
const bool colortex4Clear = false;
const bool colortex5Clear = false;
const bool colortex6Clear = true;
const bool colortex7Clear = false;
const bool colortex8Clear = false;
const bool colortex9Clear = false;
const bool colortex10Clear = false;
const bool colortex11Clear = false;
const bool colortex12Clear = true;
const bool colortex13Clear = true;
const bool colortex14Clear = false; // Cloud temporal history
const bool colortex15Clear = true;
//
const int noiseTextureResolution = 128;
const bool colortex0MipmapEnabled = true;
const bool shadowHardwareFiltering = true;
const float shadowDistanceRenderMul = 1.0;
const float entityShadowDistanceMul = 0.125; // Iris feature
const float drynessHalflife = 300.0;
const float wetnessHalflife = 300.0;
const float ambientOcclusionLevel = 1.0;
const float eyeBrightnessHalflife = 1.0f;